#!/usr/bin/env python3
"""Generates LaTeX table/macro fragments from results/experiments.csv for
report/report.tex to \\input, so every number quoted in the report is
mechanically derived from the actual dataset rather than hand-copied.

Usage:
    python3 tools/generate_report_tables.py
    python3 tools/generate_report_tables.py --csv results/experiments.csv --out-dir report/tables
"""
from __future__ import annotations

import argparse
import csv
import pathlib
import statistics

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent

PROTOCOLS = ["stop-and-wait", "go-back-n", "selective-repeat"]
PROTOCOL_LABEL = {"stop-and-wait": "Stop-and-Wait", "go-back-n": "Go-Back-N", "selective-repeat": "Selective Repeat"}
IMPAIRMENT_PATHS = ["data-error", "data-loss", "ack-error", "ack-loss"]
PATH_LABEL = {"data-error": "DATA err.", "data-loss": "DATA loss", "ack-error": "ACK err.", "ack-loss": "ACK loss"}


def load_rows(csv_path: pathlib.Path) -> list[dict]:
    with csv_path.open(newline="") as f:
        rows = list(csv.DictReader(f))
    for row in rows:
        row["probability"] = float(row["probability"])
        row["efficiency"] = float(row["efficiency"])
        row["elapsed_ms"] = float(row["elapsed_ms"])
        row["input_size_bytes"] = int(row["input_size_bytes"])
        for k in ("frames_sent", "retransmissions", "acks_received", "timeouts"):
            row[k] = int(row[k])
    return rows


def mean_by(rows, protocol, impairment_path, probability, field):
    key_path = "baseline" if probability == 0.0 else impairment_path
    values = [r[field] for r in rows
              if r["protocol"] == protocol and r["impairment_path"] == key_path and r["probability"] == probability]
    return statistics.mean(values) if values else None


def esc(s: str) -> str:
    return s.replace("_", r"\_")


def write_params(rows: list[dict], out_path: pathlib.Path) -> None:
    inputs = sorted({r["input_file"] for r in rows})
    windows = sorted({int(r["window"]) for r in rows if r["protocol"] != "stop-and-wait"})
    total_runs = len(rows)
    input_sizes = sorted({r["input_size_bytes"] for r in rows})

    lines = [
        r"% Auto-generated by tools/generate_report_tables.py -- do not edit by hand.",
        rf"\newcommand{{\NumRuns}}{{{total_runs}}}",
        rf"\newcommand{{\NumInputs}}{{{len(inputs)}}}",
        rf"\newcommand{{\InputList}}{{{', '.join(esc(i) for i in inputs)}}}",
        rf"\newcommand{{\InputSizeList}}{{{', '.join(f'{s} B' for s in input_sizes)}}}",
        rf"\newcommand{{\WindowSize}}{{{windows[0] if windows else 8}}}",
        rf"\newcommand{{\NumProbabilities}}{{5}}",
        rf"\newcommand{{\NumPaths}}{{4}}",
    ]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_baseline_summary(rows: list[dict], out_path: pathlib.Path) -> None:
    lines = [
        r"% Auto-generated by tools/generate_report_tables.py -- do not edit by hand.",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r"Protocol & Mean efficiency & Mean time (ms) & Frames sent & Retransmissions & Timeouts \\",
        r"\midrule",
    ]
    for protocol in PROTOCOLS:
        base = [r for r in rows if r["protocol"] == protocol and r["impairment_path"] == "baseline"]
        eff = statistics.mean(r["efficiency"] for r in base)
        ms = statistics.mean(r["elapsed_ms"] for r in base)
        frames = sum(r["frames_sent"] for r in base)
        retr = sum(r["retransmissions"] for r in base)
        to = sum(r["timeouts"] for r in base)
        lines.append(rf"{PROTOCOL_LABEL[protocol]} & {eff:.4f} & {ms:.3f} & {frames} & {retr} & {to} \\")
    lines += [r"\bottomrule", r"\end{tabular}%", r"}"]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_efficiency_by_path(rows: list[dict], out_path: pathlib.Path) -> None:
    lines = [
        r"% Auto-generated by tools/generate_report_tables.py -- do not edit by hand.",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{l" + "rr" * len(IMPAIRMENT_PATHS) + "}",
        r"\toprule",
    ]
    header_top = " & " + " & ".join(rf"\multicolumn{{2}}{{c}}{{{PATH_LABEL[p]}}}" for p in IMPAIRMENT_PATHS) + r" \\"
    cmid = " ".join(rf"\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(len(IMPAIRMENT_PATHS)))
    header_bottom = "Protocol " + " & p=0.1 & p=0.5" * len(IMPAIRMENT_PATHS) + r" \\"
    lines += [header_top, cmid, header_bottom, r"\midrule"]
    for protocol in PROTOCOLS:
        cells = [PROTOCOL_LABEL[protocol]]
        for path in IMPAIRMENT_PATHS:
            for p in (0.1, 0.5):
                v = mean_by(rows, protocol, path, p, "efficiency")
                cells.append(f"{v:.3f}" if v is not None else "--")
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}%", r"}"]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_retransmissions_by_path(rows: list[dict], out_path: pathlib.Path) -> None:
    lines = [
        r"% Auto-generated by tools/generate_report_tables.py -- do not edit by hand.",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{l" + "rr" * len(IMPAIRMENT_PATHS) + "}",
        r"\toprule",
    ]
    header_top = " & " + " & ".join(rf"\multicolumn{{2}}{{c}}{{{PATH_LABEL[p]}}}" for p in IMPAIRMENT_PATHS) + r" \\"
    cmid = " ".join(rf"\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(len(IMPAIRMENT_PATHS)))
    header_bottom = "Protocol " + " & p=0.1 & p=0.5" * len(IMPAIRMENT_PATHS) + r" \\"
    lines += [header_top, cmid, header_bottom, r"\midrule"]
    for protocol in PROTOCOLS:
        cells = [PROTOCOL_LABEL[protocol]]
        for path in IMPAIRMENT_PATHS:
            for p in (0.1, 0.5):
                v = mean_by(rows, protocol, path, p, "retransmissions")
                cells.append(f"{v:.1f}" if v is not None else "--")
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}%", r"}"]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--csv", type=pathlib.Path, default=PROJECT_DIR / "results" / "experiments.csv")
    parser.add_argument("--out-dir", type=pathlib.Path, default=PROJECT_DIR / "report" / "tables")
    args = parser.parse_args()

    if not args.csv.exists():
        raise SystemExit(f"{args.csv} not found -- run tools/run_experiments.py first")

    rows = load_rows(args.csv)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    write_params(rows, args.out_dir / "params.tex")
    write_baseline_summary(rows, args.out_dir / "baseline_summary.tex")
    write_efficiency_by_path(rows, args.out_dir / "efficiency_by_path.tex")
    write_retransmissions_by_path(rows, args.out_dir / "retransmissions_by_path.tex")

    print(f"wrote LaTeX fragments to {args.out_dir}")


if __name__ == "__main__":
    main()
